### ISSUE TITLE
 java.lang.reflect.InvocationTargetException (no error message)

### ISSUE THREAD

**Issue by pengzhenkun** [zhujiang521/PlayWeather#2]
A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptExecution > java.lang.reflect.InvocationTargetException (no error message)

def room_version = "2.3.0"
在 M1 芯片的mac 上编译失败
修改为 def room_version = "2.4.0-alpha03" 
解决此问题

**Comment by zhujiang521** [comment]
有问题的话就pull下代码，应该已经修复了

发自我的iPhone
